on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          url: "https://foo:bar@localhost:8000"
          file: "./examples/pipeline.yaml"